services:
  db:
    image: postgres:17
    container_name: spiratis_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    container_name: spiratis_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DATABASE_USER}:${DATABSE_PASSWORD}@db:5432/${DATSBASE_NAME}
      PYTHONUNBUFFERED: 1

volumes:
  postgres_data:
