"""add end_date to sent_games

Revision ID: 0fdb8d6b7031
Revises: dd900a1ae50f
Create Date: 2026-07-30 23:16:06.730220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdb8d6b7031'
down_revision: Union[str, Sequence[str], None] = 'dd900a1ae50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_games', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent_games', 'end_date')
    # ### end Alembic commands ###
