"""Timestamp to sent games

Revision ID: cb2f5e8ac0cb
Revises: 3aae606ce8e6
Create Date: 2026-07-30 17:01:05.575426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2f5e8ac0cb'
down_revision: Union[str, Sequence[str], None] = '3aae606ce8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем старую текстовую колонку
    op.drop_column('sent_games', 'sent_at')
    # Добавляем новую колонку с правильным типом
    op.add_column('sent_games', sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sent_games', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
