"""User timezone

Revision ID: dd900a1ae50f
Revises: a8766ac38826
Create Date: 2026-07-30 18:16:41.360553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd900a1ae50f'
down_revision: Union[str, Sequence[str], None] = 'a8766ac38826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone_offset', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE users SET timezone_offset = 0"
    )
    op.alter_column('users', 'timezone_offset', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone_offset')
    # ### end Alembic commands ###
